server:
  port: 9091
# ??? ??
debug: false
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

logging:
  level:
    com.example.projectboard: debug

    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: mihee
    password: mihee1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#      jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    # open-in-view: false
    # sql ?? ?? ?? ??
    show-sql: true
    properties:
      hibernate:
        # ???? ?? ??? ??
        format_sql: true
        # n++1 ?? ??
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  #      enabled: true
  sql:
    init:
      mode: always
#  repository 기준으로 rest api 요청할 수 있도록 도와주는 data rest 관련 설정
  data.rest:
#    기본포르:api ex) localhost:9191/api
    base-path: /api
    detection-strategy: annotated

---
spring:
  config:
    activate:
      on-profile: testdb경
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  # ??? test.database.replace: none? @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)? ?? ????.
  test:
    database:
      replace: none
